name: vigilante
description: An IoT based cold storage truck tracking and monitoring app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: 0.5.2
  firebase_auth: 0.18.3
  cloud_firestore: 0.14.3
  firebase_storage: 5.0.1
  cloud_functions: 0.7.0+1
  firebase_remote_config: 0.4.2
  firebase_messaging: 7.0.3
  firebase_dynamic_links: 0.6.2
  graphql: 4.0.0-beta.5
  graphql_flutter: 4.0.0-beta.5
  hive:
  hive_flutter:
  merge_map: ^1.0.2
  flutter_inappwebview: 4.0.0+4
  hive_generator: ^0.8.2
  geocoding: ^1.0.5
  percent_indicator: 2.1.8
  location: ^3.0.2
  geolocator: ^6.1.4
  language_pickers: ^0.2.0+1
  image_cropper: ^1.2.3
  google_maps_flutter: ^0.5.28+1
  google_maps_webservice: ^0.0.17
  flutter_google_places: ^0.2.5
  location_permissions: ^3.0.0+1  
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  artemis:
  build_runner: ^1.5.0
  json_serializable: ^3.0.0
  flutter_native_splash: ^0.1.9

flutter:

  uses-material-design: true


  assets:
    - Assets/Images/cold_splash.jpg
    - Assets/Images/404.jpg
    - Assets/Images/devices.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

